module.exports = {
  formatError: { code: "10001", message: "请求参数格式错误", result: "" },
  getNotesErr: { code: "10001", message: "获取笔记列表失败", result: "" },
  addNoteErr: { code: "10001", message: "添加笔记失败", result: "" },
  modifyNoteErr: { code: "10001", message: "修改笔记失败", result: "" },
  delNoteErr: { code: "10001", message: "删除笔记失败", result: "" },
  noFindId: { code: "10001", message: "未找到唯一标识", result: "" },
  getColorErr: { code: "10001", message: "获取颜色失败", result: "" },
  picCodeError: { code: "10001", message: "验证码错误", result: "" },
  phoneNumberNotExistsError: {
    code: "10001",
    message: "手机号未注册",
    result: "",
  },
  sendFrequentlyError: {
    code: "10001",
    message: "发送过于频繁，请稍后重试",
    result: "",
  },
  smsCodeError: { code: "10001", message: "短信验证码错误", result: "" },
  userFormateError: { code: "10001", message: "用户名或密码为空", result: "" },
  userLoginError: { code: "10001", message: "用户登录失败", result: "" },
  tokenExpiredError: { code: "10004", message: "token已过期", result: "" },
  jsonWebTokenError: { code: "10004", message: "无效的token", result: "" },
  addError: { code: "10001", message: "添加数据错误", result: "" },
  redBollCountError: { code: "10001", message: "红球数量错误", result: "" },
  bollNumToLarge: { code: "10001", message: "红蓝球大小错误", result: "" },
  qsNotExists: { code: "10001", message: "期数不存在", result: "" },
  notWeChatHost: { code: "10001", message: "微信服务校验失败", result: "" },
};
